
#ifndef NRF5x_BLE_API_H_
#define NRF5x_BLE_API_H_

#include "ble/BLE.h"
#include "ble/blecommon.h"
#include "ble/BLEInstanceBase.h"
#include "ble/BLEProtocol.h"
#include "ble/CallChainOfFunctionPointersWithContext.h"
#include "ble/CharacteristicDescriptorDiscovery.h"
#include "ble/deprecate.h"
#include "ble/DiscoveredCharacteristic.h"
#include "ble/DiscoveredCharacteristicDescriptor.h"
#include "ble/DiscoveredService.h"
#include "ble/FunctionPointerWithContext.h"
#include "ble/Gap.h"
#include "ble/GapAdvertisingData.h"
#include "ble/GapAdvertisingParams.h"
#include "ble/GapEvents.h"
#include "ble/GapScanningParams.h"
#include "ble/GattAttribute.h"
#include "ble/GattCallbackParamTypes.h"
#include "ble/GattCharacteristic.h"
#include "ble/GattClient.h"
#include "ble/GattServer.h"
#include "ble/GattServerEvents.h"
#include "ble/GattService.h"
#include "ble/SafeBool.h"
#include "ble/SecurityManager.h"
#include "ble/ServiceDiscovery.h"
#include "ble/UUID.h"


#include "ble/services/BatteryService.h"
#include "ble/services/DeviceInformationService.h"
#include "ble/services/DFUService.h"
//#include "ble/services/EddystoneConfigService.h"
//#include "ble/services/EddystoneService.h"
#include "ble/services/EnvironmentalService.h"
#include "ble/services/HealthThermometerService.h"
#include "ble/services/HeartRateService.h"
#include "ble/services/iBeacon.h"
#include "ble/services/LinkLossService.h"
#include "ble/services/UARTService.h"
#include "ble/services/URIBeaconConfigService.h"


#include "nRF5xCharacteristicDescriptorDiscoverer.h"
#include "nRF5xDiscoveredCharacteristic.h"
#include "nRF5xGap.h"
#include "nRF5xGattClient.h"
#include "nRF5xGattServer.h"
#include "nRF5xn.h"
#include "nRF5xSecurityManager.h"
#include "nRF5xServiceDiscovery.h"
#include "projectconfig.h"

#include "btle.h"
#include "btle_advertising.h"
#include "btle_clock.h"
#include "btle_discovery.h"
#include "btle_gap.h"
#include "btle_security.h"
#include "custom_helper.h"

#include "ansi_escape.h"
#include "assertion.h"
#include "binary.h"
#include "ble_error.h"
#include "common.h"
#include "compiler.h"


#endif
